# Generated by Django 4.2.7 on 2025-12-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_ingredientmaster_allergies'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='master.allergymaster'),
        ),
    ]
