# Generated by Django 4.2.7 on 2025-12-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='알레르기명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '알레르기 마스터',
                'verbose_name_plural': '알레르기 마스터',
                'db_table': 'allergy_master',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='재료명')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('default_unit', models.CharField(max_length=10, verbose_name='기본 단위')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='이모지 아이콘')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('api_source', models.CharField(blank=True, max_length=50, null=True, verbose_name='데이터 출처')),
                ('api_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='외부 API ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '식재료 마스터',
                'verbose_name_plural': '식재료 마스터',
                'db_table': 'ingredient_master',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='ingredient__name_b03add_idx'), models.Index(fields=['category'], name='ingredient__categor_decba6_idx')],
            },
        ),
    ]
