# Generated by Django 5.1.15 on 2025-12-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='알레르기명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '알레르기 마스터',
                'verbose_name_plural': '알레르기 마스터',
                'db_table': 'allergy_master',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='재료명')),
                ('category', models.CharField(choices=[('채소', '채소'), ('과일/견과', '과일/견과'), ('수산물', '수산물'), ('육류/달걀', '육류/달걀'), ('유제품', '유제품'), ('곡류', '곡류'), ('양념/오일', '양념/오일'), ('가공식품', '가공식품'), ('간편식', '간편식'), ('음료', '음료'), ('기타', '기타')], default='기타', max_length=50, verbose_name='카테고리')),
                ('default_unit', models.CharField(default='개', max_length=20, verbose_name='기본 단위')),
                ('default_storage_method', models.CharField(choices=[('냉장', '냉장'), ('냉동', '냉동'), ('실온', '실온')], default='냉장', max_length=20, verbose_name='기본 보관방법')),
                ('default_expiry_days', models.IntegerField(default=14, verbose_name='기본 유통기한(일)')),
                ('icon', models.CharField(blank=True, default='📦', max_length=10, verbose_name='이모지 아이콘')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='커스텀 아이콘 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '식재료 마스터',
                'verbose_name_plural': '식재료 마스터',
                'db_table': 'ingredient_master',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='ingredient__name_b03add_idx'), models.Index(fields=['category'], name='ingredient__categor_decba6_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngredientSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=100, unique=True, verbose_name='동의어')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='master.ingredientmaster', verbose_name='마스터 식재료')),
            ],
            options={
                'verbose_name': '식재료 동의어',
                'verbose_name_plural': '식재료 동의어',
                'db_table': 'ingredient_synonym',
            },
        ),
    ]
