# Generated by Django 4.2.7 on 2025-12-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_seed_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmaster',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='master.allergymaster'),
        ),
    ]
