# Generated by Django 4.2.7 on 2025-12-05 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='단계 번호')),
                ('description', models.TextField(verbose_name='설명')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='아이콘')),
                ('time_minutes', models.IntegerField(default=0, verbose_name='소요시간(분)')),
            ],
            options={
                'verbose_name': '조리 단계',
                'verbose_name_plural': '조리 단계',
                'db_table': 'cooking_steps',
                'ordering': ['recipe', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='레시피명')),
                ('description', models.TextField(verbose_name='설명')),
                ('cooking_time_minutes', models.IntegerField(verbose_name='조리시간(분)')),
                ('difficulty', models.CharField(max_length=20, verbose_name='난이도')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='태그')),
                ('api_source', models.CharField(blank=True, max_length=50, null=True, verbose_name='데이터 출처')),
                ('api_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='외부 API ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '레시피',
                'verbose_name_plural': '레시피',
                'db_table': 'recipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='재료명')),
                ('quantity', models.CharField(max_length=50, verbose_name='수량')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': '레시피 재료',
                'verbose_name_plural': '레시피 재료',
                'db_table': 'recipe_ingredients',
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='recipes_title_2ff3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty'], name='recipes_difficu_9b84bb_idx'),
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe'),
        ),
    ]
