# Generated by Django 5.1.15 on 2025-12-28 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='레시피명')),
                ('description', models.TextField(verbose_name='설명')),
                ('cooking_time', models.IntegerField(default=30, verbose_name='조리시간(분)')),
                ('difficulty', models.CharField(choices=[('쉬움', '쉬움'), ('보통', '보통'), ('어려움', '어려움')], default='보통', max_length=20, verbose_name='난이도')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/', verbose_name='업로드 이미지')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='태그')),
                ('category', models.CharField(choices=[('한식', '한식'), ('중식', '중식'), ('일식', '일식'), ('양식', '양식'), ('디저트', '디저트'), ('샐러드', '샐러드'), ('퓨전', '퓨전'), ('기타', '기타')], default='기타', max_length=50, verbose_name='카테고리')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개여부')),
                ('source', models.CharField(choices=[('api', 'API'), ('user', '사용자'), ('ai', 'AI 생성')], default='api', max_length=50, verbose_name='출처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('scraped_by', models.ManyToManyField(blank=True, related_name='scraped_recipes', to=settings.AUTH_USER_MODEL, verbose_name='스크랩한 유저')),
            ],
            options={
                'verbose_name': '레시피',
                'verbose_name_plural': '레시피',
                'db_table': 'recipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='단계 번호')),
                ('description', models.TextField(verbose_name='설명')),
                ('icon', models.CharField(blank=True, default='🍳', max_length=10, verbose_name='아이콘')),
                ('time_minutes', models.IntegerField(default=0, verbose_name='소요시간(분)')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'verbose_name': '조리 단계',
                'verbose_name_plural': '조리 단계',
                'db_table': 'cooking_steps',
                'ordering': ['recipe', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='재료명')),
                ('amount', models.CharField(blank=True, default='', max_length=50, verbose_name='분량')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_ingredients', to='master.ingredientmaster', verbose_name='마스터 식재료')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': '레시피 재료',
                'verbose_name_plural': '레시피 재료',
                'db_table': 'recipe_ingredients',
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='recipes_title_2ff3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty'], name='recipes_difficu_9b84bb_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['category'], name='recipes_categor_1ac69a_idx'),
        ),
    ]
