# Generated by Django 4.2.7 on 2025-12-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='기타', max_length=50, verbose_name='카테고리'),
        ),
    ]
