# Generated by Django 5.2 on 2025-12-23 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='scraped_by',
            field=models.ManyToManyField(blank=True, related_name='scraped_recipes', to=settings.AUTH_USER_MODEL, verbose_name='스크랩한 유저'),
        ),
    ]
