# Generated by Django 5.1.15 on 2025-12-28 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='재료명')),
                ('quantity', models.FloatField(default=1, verbose_name='수량')),
                ('unit', models.CharField(default='개', max_length=20, verbose_name='단위')),
                ('storage_method', models.CharField(choices=[('냉장', '냉장'), ('냉동', '냉동'), ('실온', '실온')], default='냉장', max_length=20, verbose_name='보관방법')),
                ('expiry_date', models.DateField(verbose_name='유통기한')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ingredients', to='master.ingredientmaster', verbose_name='마스터 식재료')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 식재료',
                'verbose_name_plural': '사용자 식재료',
                'db_table': 'user_ingredients',
                'ordering': ['expiry_date', 'name'],
                'indexes': [models.Index(fields=['user', 'expiry_date'], name='user_ingred_user_id_0334f7_idx'), models.Index(fields=['user', 'is_deleted'], name='user_ingred_user_id_3b7146_idx')],
            },
        ),
    ]
