# Generated by Django 4.2.7 on 2025-12-05 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='재료명')),
                ('quantity', models.FloatField(verbose_name='수량')),
                ('unit', models.CharField(choices=[('g', '그램'), ('ml', '밀리리터'), ('개', '개'), ('봉', '봉'), ('팩', '팩')], default='g', max_length=10, verbose_name='단위')),
                ('storage_method', models.CharField(choices=[('냉장', '냉장'), ('냉동', '냉동'), ('실온', '실온')], max_length=10, verbose_name='보관방법')),
                ('expiry_date', models.DateField(verbose_name='유통기한')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/')),
                ('master_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ingredients', to='master.ingredientmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 식재료',
                'verbose_name_plural': '사용자 식재료',
                'db_table': 'user_ingredients',
                'ordering': ['expiry_date', 'name'],
                'indexes': [models.Index(fields=['user', 'expiry_date'], name='user_ingred_user_id_0334f7_idx'), models.Index(fields=['user', 'name'], name='user_ingred_user_id_190831_idx')],
            },
        ),
    ]
