# Generated by Django 5.2 on 2025-12-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useringredient',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카테고리'),
        ),
    ]
