# Generated by Django 5.2 on 2025-12-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0002_useringredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='unit',
            field=models.CharField(default='개', max_length=20, verbose_name='단위'),
        ),
    ]
