# Generated by Django 5.2 on 2025-12-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0003_alter_useringredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='storage_method',
            field=models.CharField(default='냉장', max_length=20, verbose_name='보관방법'),
        ),
    ]
