# Generated by Django 5.2 on 2025-12-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0004_alter_useringredient_storage_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='useringredient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
        migrations.AddField(
            model_name='useringredient',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
    ]
